### ISSUE TITLE
remove `__pycache__` folders?

### ISSUE THREAD

**Issue by metzm** [mundialis/actinia-stac-plugin#1]
There are `__pycache__` folders inside the folders, they should most probably be removed because they are generated when installing the plugin?

**Comment by metzm** [comment]
Same for the `.eggs` and `build` folders?

**Comment by joaherrerama** [comment]
I removed already the folders and the changes are on commits [a28a3c1](https://github.com/mundialis/actinia-stac-plugin/commit/a28a3c1037574ef29a0c8d62c96a15512137f304) , [1a4d10c](https://github.com/mundialis/actinia-stac-plugin/commit/1a4d10c483b44bb5cd132b6694445a9d9eeb8e5a), [62af968](https://github.com/mundialis/actinia-stac-plugin/commit/62af9687a9c058e58583ad8146173b2316939145)

**Comment by marcjansen** [comment]
How about adding a `.gitignore` to make common & usually unccommitted files (inspiration maybe from [here](https://github.com/github/gitignore/blob/master/Python.gitignore)) being ignored from `git`?

**Comment by joaherrerama** [comment]
Indeed, I already create the `.gitignore`, I will upload it in the next pull request 👍🏽

**Comment by marcjansen** [comment]
Great. If possible in a seperate one, one enhancement at a time ;-)

**Comment by joaherrerama** [comment]
Here is the pull request  #14  regarding the `.gitignore` file
