### ISSUE TITLE
[Discover] List - Create endpoint `/stac/instances/<stac_instance_id>`

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia-stac-plugin#11]
returns a list of all already registered STAC collections from a certain instance

**Comment by joaherrerama** [comment]
A minor thing, but I think, hyphens are not allowed in URL rules right? Instead, we can use underscore, right?

**Comment by mmacata** [comment]
Might be true. I changed it and will also change for others. I wanted to keep it consistent with the variable name but if it doesn't work, we need to change it, yes :grimacing:
