### ISSUE TITLE
[COMMENT] IDs redundance in the endpoint  `stac/collections`

### ISSUE THREAD

**Issue by joaherrerama** [mundialis/actinia-stac-plugin#25]
The current endpoint list all collections stored in Redis regardless of the instance. The comment was given due to the fact that in this listing might happen that two or more `COLLECTIONS` provided from different endpoints might have the same ID. The suggestion was to create a prefix "index" that works as identifier for the providers and the STAC read. 

>  **Highlights:**

- The `ID` inside each `STAC Collection` is given by the provider, modifying them might not be a good approach.
- The separation by the identifies in the `stac/collections` endpoint might work, but the effects in the reading in the OpenEO driver must be considered.
- The concept of **intances** was not clear and maybe we can think about it relevance inside `actinia` and `OpenEO`

**Comment by mmacata** [comment]
Already done via replacement of ID, see my comment above.
