### ISSUE TITLE
Add pipeline for linting

### ISSUE THREAD

**Issue by mmacata** [mundialis/actinia-stac-plugin#4]
For each commit, a pipeline should be triggered to look at the PEP8 style guide rules. If they are not considered well, pipeline should fail. If there are valid reasons, a `.flake8` file can be used to ignore certain violations.

A running example can be seen [here](https://github.com/mundialis/actinia_core/blob/main/.github/workflows/flake8.yml)

**Comment by joaherrerama** [comment]
I was getting in depth with Linters and Fixers and I found this [Super Linter](https://github.com/github/super-linter), it checks also the docker and sh files. Would be a good idea to implement? @marcjansen @mmacata
